workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: https://raw.githubusercontent.com/LukeHagar/plex-api-spec/refs/heads/main/plex-api-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi
targets:
    plexswift:
        target: swift
        source: plexapi
        codeSamples:
            labelOverride: 
                fixedValue: PlexSwift
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-swift-plexswift
